# Verdaccio configuration
#   - Look here for information about this file:
#       https://verdaccio.org/docs/en/configuration.html
#   - Look here for more config file examples:
#       https://github.com/verdaccio/verdaccio/tree/master/conf

# path to a directory with all packages
storage: /verdaccio/storage/data
# path to a directory with plugins to include
plugins: /verdaccio/plugins

web:
  enable: false
  title: Verdaccio

auth:
  htpasswd:
    file: /verdaccio/storage/htpasswd

# a list of other known registries we can talk to
uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  '**':
    access: $all
    publish: $all
    unpublish: $all
    proxy: npmjs

middlewares:
  audit:
    enabled: true

# log settings
logs:
  - {type: stdout, format: pretty, level: http}
